---
ingress:
  - 0.1.0 Initial Chart
  - 0.1.1 Change helm-toolkit dependency version to ">= 0.1.0"
  - 0.1.2 Update to container image repo k8s.gcr.io
  - 0.2.0 Update default Kubernetes API for use with Helm v3
  - 0.2.1 Use HostToContainer mountPropagation
  - 0.2.2 Use full image ref for docker official images
  - 0.2.3 Uplift ingress to 0.42.0
  - 0.2.4 Update htk requirements
  - 0.2.5 Migrate Ingress resources to networking.k8s.io/v1
  - 0.2.6 Add option to assign VIP as externalIP
  - 0.2.7 Enable taint toleration for Openstack services jobs
  - 0.2.8 Uplift ingress to 1.1.3
  - 0.2.9 Added OCI registry authentication
  - 0.2.10 Update neutron images to xena release
  - 0.2.11 Fix resource name in the role
...
